version: "3"
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: user
    volumes:
      - ./database_scripts:/docker-entrypoint-initdb.d:z
  
  project:
    build:
      args:
        - DJANGO_SETTINGS_MODULE=project.settings.testing
        - MODE=testing
      context: .
    depends_on:
      - database
    volumes:
      - ./:/code:z
    ports:
      - 8000:80
