"""
This module describes basic terminal commands for simplifying operations with
docker-compose.

ATENTION!!! Some commands requires superuser permissions to work properly (
this is because of cache files generated by postgres and python inside docker are
assigned to root, so in order to remove them you have to be root). Check code if you
don't trust. To allow commands to be executed with root rights please set environmental
variable HELPERS_ALLOW_SUDO to true and enter your password (if you have it). If the
variable is not set to true commands will use current user's rights.

The whole management module is ignored by tests since there're not much things that
can have reasonable tests (and I'm lazy). If you decide to improve this, feel free
to add tests.
"""
import subprocess
import os

from .constants import (
    FILE_WITH_IMAGE_STATUS,
    DEVELOPMENT_IMAGE,
    TEST_IMAGE,
    ALLOW_SUDO_USAGE_ENV_VAR,
)


class BaseTerminalCommand:
    command = None
    commands_to_run_before = None
    commands_to_run_after = None
    sudo_required = False

    def start(self):
        self._run_before()
        self._run()
        self._run_after()

    def _run_before(self):
        if self.commands_to_run_before:
            for command in self.commands_to_run_before:
                command.start()

    def _run(self):
        subprocess.run(self.full_command, shell=True)

    def _run_after(self):
        if self.commands_to_run_after:
            for command in self.commands_to_run_after:
                command.start()

    @property
    def full_command(self):
        if (
            os.environ.get(ALLOW_SUDO_USAGE_ENV_VAR, None)
            and self.sudo_required
        ):
            return f"sudo {self.command}"
        else:
            return self.command


class RemovePycacheTerminalCommand(BaseTerminalCommand):
    command = "rm -rf **/__pycache__"
    sudo_required = True


class ClearDatabaseTerminalCommand(BaseTerminalCommand):
    command = "rm -rf __postgres_data__"
    sudo_required = True


class ResetImageStatusTerminalCommand(BaseTerminalCommand):
    command = f"rm {FILE_WITH_IMAGE_STATUS}"


class CreateImageStatusTerminalCommand(BaseTerminalCommand):
    def __init__(self, status):
        self.status = status

    def _run(self):
        self._write_to_file()

    def _write_to_file(self):
        with open(FILE_WITH_IMAGE_STATUS, "w") as file:
            file.write(self.status)


class StartDatabaseTerminalCommand(BaseTerminalCommand):
    command = "docker-compose up -d database"


class StartTestDatabaseTerminalCommand(BaseTerminalCommand):
    command = "docker-compose -f docker-compose.test.yaml up -d database"


class StopServicesTerminalCommand(BaseTerminalCommand):
    commands_to_run_before = [RemovePycacheTerminalCommand()]
    command = "docker-compose down"


class LogsTerminalCommand(BaseTerminalCommand):
    command = "docker-compose logs"


class ListTerminalCommand(BaseTerminalCommand):
    command = "docker-compose list"


class RunTestsTerminalCommand(BaseTerminalCommand):
    commands_to_run_before = [
        StopServicesTerminalCommand(),
        StartTestDatabaseTerminalCommand(),
    ]
    command = (
        "docker-compose -f docker-compose.test.yaml up -d"
        " && docker-compose logs -f project"
    )


class RunTestsInShellTerminalCommand(BaseTerminalCommand):
    commands_to_run_before = [
        StopServicesTerminalCommand(),
        StartTestDatabaseTerminalCommand(),
    ]
    command = (
        "docker-compose -f docker-compose.test.yaml run project /bin/bash"
    )


class RunAppTerminalCommand(BaseTerminalCommand):
    commands_to_run_before = [
        StopServicesTerminalCommand(),
        StartDatabaseTerminalCommand(),
    ]
    command = "docker-compose up -d"


class RunAppInShellTerminalCommand(BaseTerminalCommand):
    commands_to_run_before = [
        StopServicesTerminalCommand(),
        StartDatabaseTerminalCommand(),
    ]
    command = "docker-compose run -p 8000:80 project /bin/bash"


class RemoveDockerImage(BaseTerminalCommand):
    command = "docker-compose build --no-cache"
